import os
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# 1. Generate Synthetic Network Flow Dataset
# Features:
# 0: duration (seconds)
# 1: protocol (1=TCP, 2=UDP, 3=ICMP)
# 2: packet_count
# 3: byte_count
# 4: src_port
# 5: dst_port
# 6: flag_syn
# 7: flag_ack
# 8: flag_fin

print("Generating synthetic network flow dataset...")
np.random.seed(42)
n_samples = 5000

data = []
labels = []

for _ in range(n_samples):
    traffic_type = np.random.choice([0, 1, 2, 3], p=[0.6, 0.15, 0.15, 0.10])
    
    if traffic_type == 0:  # BENIGN
        duration = np.random.exponential(10.0) + 0.1
        protocol = np.random.choice([1, 2], p=[0.7, 0.3])
        packet_count = np.random.randint(5, 500)
        byte_count = packet_count * np.random.randint(64, 1400)
        src_port = np.random.randint(1024, 65535)
        dst_port = np.random.choice([80, 443, 53, 123])
        flag_syn = 1 if protocol == 1 else 0
        flag_ack = packet_count // 2 if protocol == 1 else 0
        flag_fin = 1 if protocol == 1 else 0
        
    elif traffic_type == 1:  # DDoS
        duration = np.random.uniform(0.01, 1.0)
        protocol = 1  # TCP SYN flood mostly
        packet_count = np.random.randint(5000, 20000)
        byte_count = packet_count * 64  # Small packets
        src_port = np.random.randint(1024, 65535)
        dst_port = 80
        flag_syn = packet_count
        flag_ack = 0
        flag_fin = 0
        
    elif traffic_type == 2:  # Port Scan
        duration = np.random.uniform(0.1, 2.0)
        protocol = 1
        packet_count = np.random.randint(1, 5)
        byte_count = packet_count * 40  # Headers only
        src_port = np.random.randint(1024, 65535)
        dst_port = np.random.randint(1, 1024)  # Scanning well-known ports
        flag_syn = packet_count
        flag_ack = 0
        flag_fin = 0
        
    else:  # Brute Force
        duration = np.random.uniform(2.0, 30.0)
        protocol = 1  # SSH/FTP
        packet_count = np.random.randint(50, 200)
        byte_count = packet_count * 100
        src_port = np.random.randint(1024, 65535)
        dst_port = np.random.choice([21, 22])  # FTP or SSH
        flag_syn = np.random.randint(2, 5)
        flag_ack = packet_count // 2
        flag_fin = np.random.randint(1, 3)

    data.append([duration, protocol, packet_count, byte_count, src_port, dst_port, flag_syn, flag_ack, flag_fin])
    labels.append(traffic_type)

X = np.array(data)
y = np.array(labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Random Forest Classifier...")
# We keep n_estimators small (e.g. 10 trees, max_depth=8) to keep the generated Go code compact and extremely fast.
clf = RandomForestClassifier(n_estimators=10, max_depth=8, random_state=42)
clf.fit(X_train, y_train)
score = clf.score(X_test, y_test)
print(f"Model accuracy on test set: {score * 100:.2f}%")

# 2. Generator function to compile Decision Trees into Go code
def export_tree_to_go(tree, tree_index):
    left = tree.children_left
    right = tree.children_right
    threshold = tree.threshold
    feature = tree.feature
    value = tree.value  # Contains class counts at each leaf node

    lines = []
    lines.append(f"func evaluateTree{tree_index}(features []float64) int {{")
    
    def recurse(node, depth):
        indent = "\t" * depth
        if left[node] == -1:  # Leaf node
            # Get the class with the maximum count
            class_counts = value[node][0]
            predicted_class = int(np.argmax(class_counts))
            return f"{indent}return {predicted_class}"
        else:
            feat_idx = feature[node]
            thresh = threshold[node]
            
            go_code = f"{indent}if features[{feat_idx}] <= {thresh:.6f} {{\n"
            go_code += recurse(left[node], depth + 1) + "\n"
            go_code += f"{indent}}} else {{\n"
            go_code += recurse(right[node], depth + 1) + "\n"
            go_code += f"{indent}}}"
            return go_code

    lines.append(recurse(0, 1))
    lines.append("}")
    return "\n".join(lines)

# 3. Create model.go containing the random forest evaluator in Go
go_filename = "../pkg/classifier/model.go"
os.makedirs(os.path.dirname(go_filename), exist_ok=True)

print(f"Exporting model to {go_filename}...")

go_code = """// Code generated by ml/train.py. DO NOT EDIT.
package classifier

// Predict evaluates the input features using the trained Random Forest model (majority vote).
// Features vector layout:
// 0: duration (sec)
// 1: protocol (1=TCP, 2=UDP, 3=ICMP)
// 2: packet_count
// 3: byte_count
// 4: src_port
// 5: dst_port
// 6: flag_syn
// 7: flag_ack
// 8: flag_fin
func Predict(features []float64) int {
\tvotes := make(map[int]int)
"""

# Append evaluation of each tree
for i in range(clf.n_estimators):
    go_code += f"\tvotes[evaluateTree{i}(features)]++\n"

go_code += """
\tmaxVotes := -1
\tpredictedClass := 0
\tfor class, voteCount := range votes {
\t\tif voteCount > maxVotes {
\t\t\tmaxVotes = voteCount
\t\t\tpredictedClass = class
\t\t}
\t}
\treturn predictedClass
}
"""

# Append the actual tree functions
for i, estimator in enumerate(clf.estimators_):
    go_code += "\n" + export_tree_to_go(estimator.tree_, i) + "\n"

with open(go_filename, "w") as f:
    f.write(go_code)

print("Export completed successfully!")
