// Code generated by ml/train.py. DO NOT EDIT.
package classifier

// Predict evaluates the input features using the trained Random Forest model (majority vote).
// Features vector layout:
// 0: duration (sec)
// 1: protocol (1=TCP, 2=UDP, 3=ICMP)
// 2: packet_count
// 3: byte_count
// 4: src_port
// 5: dst_port
// 6: flag_syn
// 7: flag_ack
// 8: flag_fin
func Predict(features []float64) int {
	votes := make(map[int]int)
	votes[evaluateTree0(features)]++
	votes[evaluateTree1(features)]++
	votes[evaluateTree2(features)]++
	votes[evaluateTree3(features)]++
	votes[evaluateTree4(features)]++
	votes[evaluateTree5(features)]++
	votes[evaluateTree6(features)]++
	votes[evaluateTree7(features)]++
	votes[evaluateTree8(features)]++
	votes[evaluateTree9(features)]++

	maxVotes := -1
	predictedClass := 0
	for class, voteCount := range votes {
		if voteCount > maxVotes {
			maxVotes = voteCount
			predictedClass = class
		}
	}
	return predictedClass
}

func evaluateTree0(features []float64) int {
	if features[2] <= 2763.500000 {
		if features[5] <= 24.500000 {
			if features[6] <= 1.500000 {
				return 2
			} else {
				if features[2] <= 27.000000 {
					return 2
				} else {
					return 3
				}
			}
		} else {
			if features[6] <= 1.500000 {
				if features[3] <= 672.500000 {
					return 2
				} else {
					return 0
				}
			} else {
				return 2
			}
		}
	} else {
		return 1
	}
}

func evaluateTree1(features []float64) int {
	if features[2] <= 4.500000 {
		return 2
	} else {
		if features[2] <= 2763.500000 {
			if features[6] <= 1.500000 {
				return 0
			} else {
				return 3
			}
		} else {
			return 1
		}
	}
}

func evaluateTree2(features []float64) int {
	if features[6] <= 1.500000 {
		if features[3] <= 502.500000 {
			return 2
		} else {
			return 0
		}
	} else {
		if features[6] <= 2516.000000 {
			if features[8] <= 0.500000 {
				return 2
			} else {
				return 3
			}
		} else {
			return 1
		}
	}
}

func evaluateTree3(features []float64) int {
	if features[3] <= 562.500000 {
		return 2
	} else {
		if features[2] <= 2793.500000 {
			if features[6] <= 1.500000 {
				return 0
			} else {
				return 3
			}
		} else {
			return 1
		}
	}
}

func evaluateTree4(features []float64) int {
	if features[6] <= 1.500000 {
		if features[2] <= 3.000000 {
			return 2
		} else {
			return 0
		}
	} else {
		if features[2] <= 2613.500000 {
			if features[5] <= 26.000000 {
				if features[8] <= 0.500000 {
					return 2
				} else {
					return 3
				}
			} else {
				return 2
			}
		} else {
			return 1
		}
	}
}

func evaluateTree5(features []float64) int {
	if features[2] <= 2763.500000 {
		if features[5] <= 23.500000 {
			if features[7] <= 12.500000 {
				return 2
			} else {
				return 3
			}
		} else {
			if features[3] <= 645.500000 {
				return 2
			} else {
				return 0
			}
		}
	} else {
		return 1
	}
}

func evaluateTree6(features []float64) int {
	if features[5] <= 23.500000 {
		if features[0] <= 1.957287 {
			return 2
		} else {
			return 3
		}
	} else {
		if features[2] <= 2781.000000 {
			if features[0] <= 1.989768 {
				if features[7] <= 1.000000 {
					if features[6] <= 0.500000 {
						return 0
					} else {
						return 2
					}
				} else {
					return 0
				}
			} else {
				return 0
			}
		} else {
			return 1
		}
	}
}

func evaluateTree7(features []float64) int {
	if features[0] <= 2.003863 {
		if features[3] <= 1550.000000 {
			return 2
		} else {
			if features[6] <= 2514.500000 {
				return 0
			} else {
				return 1
			}
		}
	} else {
		if features[8] <= 1.500000 {
			if features[3] <= 19974.000000 {
				if features[6] <= 1.500000 {
					return 0
				} else {
					return 3
				}
			} else {
				return 0
			}
		} else {
			return 3
		}
	}
}

func evaluateTree8(features []float64) int {
	if features[2] <= 4.500000 {
		return 2
	} else {
		if features[2] <= 2763.500000 {
			if features[5] <= 37.500000 {
				return 3
			} else {
				return 0
			}
		} else {
			return 1
		}
	}
}

func evaluateTree9(features []float64) int {
	if features[6] <= 1.500000 {
		if features[5] <= 447.500000 {
			if features[5] <= 49.000000 {
				return 2
			} else {
				if features[3] <= 502.500000 {
					return 2
				} else {
					return 0
				}
			}
		} else {
			return 2
		}
	} else {
		if features[6] <= 2516.000000 {
			if features[7] <= 12.500000 {
				return 2
			} else {
				return 3
			}
		} else {
			return 1
		}
	}
}
